name: Bug Report
description: File a bug report
title: 'bug: '
body:
  - type: markdown
    attributes:
      value: |
        **Remember:** These are bug reports related to enhancements provided by RHF+. If you are having issues with React Hook Form itself, please file an issue in the [React Hook Form repository](https://github.com/react-hook-form/react-hook-form/issues).
  - type: input
    id: version
    attributes:
      label: RHF+ Version
      description: e.g. v7.56.1-plus.0
    validations:
      required: true
  - type: input
    id: codesandbox
    attributes:
      label: Reproduction Link
      description: Please provide a link to a minimal reproduction of the bug using a tool like [CodeSandbox](https://codesandbox.io/). This helps us to quickly identify and fix the issue.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Steps to reproduce
      placeholder: Tell us what you see!
      value: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: what-expect
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and Errors
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/bombillazo/rhf-plus/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
