name: Bug Report
description: File a bug report
title: 'bug: '
body:
  - type: markdown
    attributes:
      value: |
        **Remember:** These are bug reports related to enhancements provided by RHF+. If you are having issues with React Hook Form itself, please file an issue in the [React Hook Form repository](https://github.com/react-hook-form/react-hook-form/issues).
  - type: input
    id: version
    attributes:
      label: Version Number
      description: What's the RHV+ version?
    validations:
      required: true
  - type: input
    id: codesandbox
    attributes:
      label: CodeSandbox/Expo Snack Link
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Steps to reproduce
      placeholder: Tell us what you see!
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: what-expect
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/bombillazo/rhf-plus/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
